//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_db
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_db()
        {
            this.result_db = new HashSet<result_db>();
            this.user_team_db = new HashSet<user_team_db>();
        }
    
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_pwd { get; set; }
        public string user_email { get; set; }
        public Nullable<System.DateTime> user_bday { get; set; }
        public string user_country { get; set; }
        public string user_fav_team { get; set; }
        public Nullable<double> user_per_factor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<result_db> result_db { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_team_db> user_team_db { get; set; }
    }
}
