//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_team_db
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_team_db()
        {
            this.user_player_db = new HashSet<user_player_db>();
        }
    
        public int event_id { get; set; }
        public int user_id { get; set; }
        public string user_team_name { get; set; }
        public int user_team_id { get; set; }
        public string star_bats { get; set; }
        public string star_bowl { get; set; }
    
        public virtual event_db event_db { get; set; }
        public virtual user_db user_db { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_player_db> user_player_db { get; set; }
    }
}
