//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_player_db
    {
        public int user_team_id { get; set; }
        public string player_team { get; set; }
        public string player_type { get; set; }
        public string player_name { get; set; }
        public string player_image { get; set; }
        public double player_value { get; set; }
    
        public virtual user_team_db user_team_db { get; set; }
    }
}
